### ISSUE TITLE
Impossible d'avoir accès à l'intégralité du projet.

### ISSUE THREAD

**Issue by koffisani** [Classroom-Koffi-Sani/gestion-scolarite#1]
Bonjour à tous,

@wisdomtohe @mvincentbb 
Le lien https://github.com/mvincentbb/Gestion_Ecole/tree/649ec20dd87fc9fe15a11ec6ae8ecc2a6005e14c est inaccessible.

**Comment by koffisani** [comment]
Allo @wisdomtohe @mvincentbb

**Comment by mvincentbb** [comment]
C ‘ est bon maintenant monsieur vous avez accès au projet . Excusez nous

**Comment by koffisani** [comment]
C'était en mode privé ?

**Comment by mvincentbb** [comment]
Oui Monsieur

**Comment by koffisani** [comment]
Ok. Et concernant la base de données ?

**Comment by mvincentbb** [comment]
On a ajoute la base de donnée le fichier schoolmgmt.sql et  schoolmgmt.txt

**Comment by mvincentbb** [comment]
Svp monsieur j’ai pas compris . A quelle partie vous n’avez pas accès

**Comment by koffisani** [comment]
Je crois que c'est bon maintenant.

**Comment by mvincentbb** [comment]
Merci Monsieur

**Comment by koffisani** [comment]
Bien.
